mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.sbitech.mapper: debug

server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://43.143.94.191:35432/aireferee
    username: aireferee
    password: aireferee
    driver-class-name: org.postgresql.Driver
# 在spring配置下添加
jwt:
  secret: mySecretKeyForMartialArtsRefereeSystemShouldBeVeryLongAndSecure123456789
  expiration: 86400000  # 24小时，单位毫秒

pdf:
  scan:
    path: C:\Users\dlnsupport\Documents\Project\武术系统\userFront\public\report